# Pre-commit hooks configuration for shopping-assistant
# Run `pre-commit install` to set up the git hooks
# Run `pre-commit run --all-files` to run all hooks on all files

repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b  # frozen: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
        args: [--line-length=100]

  # Ruff - Fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0acff885bcb16381b67930fefb91e460202f172c  # frozen: v0.12.10
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # MyPy - Static type checker
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 412de98d50e846f31ea6f4b0ad036f2c24a7a024  # frozen: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies: [types-redis, types-requests]
        args: [--ignore-missing-imports]

  # Built-in pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: debug-statements
      - id: detect-private-key

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 2d0b675b04c80ae42277e10500db06a0a37bae17  # frozen: 1.8.6
    hooks:
      - id: bandit
        args: [-r, app/, -ll, -x, tests/]

  # Docstring formatting
  - repo: https://github.com/PyCQA/docformatter
    rev: e73b8ba0c1316be565983236c72e653ad44e6b66  # frozen: v1.7.7
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=100, --wrap-descriptions=100]

  # Import sorting (handled by ruff, but keeping as backup)
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.13.2
  #   hooks:
  #     - id: isort
  #       args: ["--profile", "black", "--line-length", "100"]

# Configuration for pre-commit.ci (if using)
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: [mypy]  # Skip mypy in CI as it requires dependencies
  submodules: false
